name: Build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Pico SDK and toolchain
      run: |
        git clone -b "1.5.0" --depth=1 https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init --depth=1
        cd ..
        sudo apt-get update
        sudo apt-get install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
    - name: Install PanDoc and LaTeX
      run: |
        sudo apt-get install pandoc texlive-latex-recommended texlive-latex-extra texlive-fonts-extra
    - name: Install Eisvogel PanDoc template
      run: |
        wget https://github.com/Wandmalfarbe/pandoc-latex-template/releases/download/v2.0.0/Eisvogel-2.0.0.zip
        unzip Eisvogel-2.0.0.zip eisvogel.latex
    - name: Build binaries
      env:
        PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk
      run: |
        cmake -B build
        make -C build
    - name: Build tools
      run: |
        zip wificred-store.zip wificred-store.py wificred-delete.uf2
    - name: Build documentation
      run: |
        git log -1 --date=short "--format=format:date: %cd %h%n" >> README.yaml
        pandoc -s -o README.pdf -t latex --metadata-file=README.yaml --template eisvogel README.md
    - name: Save binary as pre-release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest firmware"
        prerelease: false
        files: |
          build/picowifi.uf2
          wificred-store.zip
          README.pdf
